---
- name: terraform destroy
  shell:
    cmd: terraform destroy -force
    chdir: aws-dev-env-template/terraform
  register: tf_destroy
  changed_when: "not tf_destroy.stdout | search('Destroy complete! Resources: 0 destroyed.')"
