---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - import_tasks: tasks/terraform/setup.yml
  - import_tasks: tasks/terraform/apply.yml

- import_playbook: aws-dev-env-template/ansible/bootstrap.yml

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - import_tasks: tasks/setup_ssh.yml

- hosts: managed
  gather_facts: no
  become: yes
  tasks:
  - import_tasks: tasks/package.yml
  - import_tasks: tasks/vnc.yml
