---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - include_tasks: tasks/local.yml

- hosts: managed
  become: yes
  tasks:
  - include_tasks: tasks/package.yml
  - include_tasks: tasks/vnc.yml
