---
- name: Install Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - lxde
    - tmux
    - tigervnc-standalone-server
    - x11-apps
    - xorg
    - xserver-xorg-video-all
