---
- name: Setup TigerVNC service
  template:
    src: templates/vncserver@:1.service.j2
    dest: /etc/systemd/system/vncserver@:1.service

- name: Enable TigerVNC service
  service:
    name: vncserver@:1.service
    enabled: yes
    state: started
