region = "us-west-2"
availability-zone = "us-west-2a"
# ami-id = ""
# ebs-size = 10
# ebs-snapshot-retention-days = 30
# ebs-snapshot-schedule = "cron(0 9 ? * MON *)"
# ebs-type = "gp2"
# instance-type = "t2.micro"
primary-user = "lyang"
# ssh-key-dir = "~/.ssh/aws-dev-env/"
# system-user = "ec2-user"
